unit NamikoTypes;

interface

uses
  Winapi.Windows, System.UITypes, System.Generics.Collections;

type
  TNetResult = (OK, BadFormat, BadKey, BadTime, BadData, BadLen, Hexied, IntErr);
// TComment -> TLiveComment -> TRenderUnit
// TCommentCollection -> TLiveCommentCollection -> TRenderUnitQueue

// TComment & TCommentCollection
type
  TAuthorSource = (Internet, Console, XML);
type
  TCommentAuthor = record
    Source: TAuthorSource;
    Address: string;
  end;
type
  TCommentEffectType = (Scroll, UpperFixed, LowerFixed);
type
  TCommentEffect = record
    Display: TCommentEffectType;
    StayTime: SmallInt;
    RepeatCount: SmallInt;
    Speed: SmallInt;
  end;
type
  TCommentFormat = record
    DefaultName: Boolean;
    DefaultSize: Boolean;
    DefaultColor: Boolean;
    DefaultStyle: Boolean;
    FontName: WideString;
    FontSize: Single;
    FontColor: TAlphaColor;
    FontStyle: Integer; // Bitwise OR of TFontStyles
  end;
type
  TCommentStatus = (
    Created,    // [IDLE] Generated, not listed nor dispatched by MAIN THREAD
    Pending,    // [IDLE] Dispatched at least once but not send into TLiveCommentCollection
    Starting,   // [LIVE] Sent to TLiveCommentCollection and just to be rendered
    Waiting,    // [LIVE] Render decided not to draw it due to no channels left etc. Should be RARE
    Displaying, // [LIVE] Rendering and updating cycle
    Removing,   // [LIVE] Marked as displayed by render and render should remove it from TLiveCommentCollection
    Removed     // [IDLE] Marked as displayed or deleted comment and not in TLiveCommentCollection
  );
type
  TComment = class(TObject)
    Time: TTime;
    Content: string;
    Author: TCommentAuthor;
    Format: TCommentFormat;
    Effect: TCommentEffect;
    Status: TCommentStatus;
  protected
    FID: Integer;
    class var MaxID: Integer;
  public
    property ID: Integer read FID;
    constructor Create();
  end;
type
  PComment = ^TComment;
type
  TCommentCollection = TObjectList<TComment>;
type
  PCommentCollection = ^TCommentCollection;
// TLiveComment & TLiveCommentCollection
type
  TLiveCommentStatus = (
    LCreated,   // Generated by dispatcher and not complete
    LWait,      // Not calculated due to limitation
    LMoving,    // Do move/display
    LDelete     // Allow render to remove it
  );
type
  TLiveComment = class(TObject)
    Body: TComment;
    Status: TLiveCommentStatus;
    ChannelLayer: Integer;
    ChannelFrom: Integer;
    ChannelTo: Integer;
    Height: Integer;
    Width: Integer;
    Left: Integer;
    Top: Integer;
    Cycles: Cardinal;
    CycleValue: Cardinal;
  end;
type
  PLiveComment = ^TLiveComment;
type
  TLiveCommentCollection = TObjectList<TLiveComment>;
type
  PLiveCommentCollection = ^TLiveCommentCollection;
// TRenderUnit & TRenderUnitQueue
type
  TRenderUnit = record
    hSrcDC: HDC;
    hDC: HDC;
    hBitmap: HBITMAP;
  end;
type
  TRenderUnitQueue = TQueue<TRenderUnit>;
type
  PRenderUnitQueue = ^TRenderUnitQueue;

implementation

constructor TComment.Create;
begin
  inherited Create();
  Inc(MaxID);
  Self.FID := MaxID;
end;

end.
